# Generated by Django 3.1.3 on 2020-11-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendmodel',
            name='tlink',
        ),
    ]
