# Generated by Django 3.1.3 on 2020-11-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_one', '0002_remove_trendmodel_tlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtitle', models.CharField(max_length=120)),
                ('rimage', models.ImageField(upload_to='')),
                ('rprice', models.CharField(max_length=50)),
            ],
        ),
    ]
