# Generated by Django 3.1.3 on 2020-11-11 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_one', '0003_relatedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedmodel',
            name='rlink',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendmodel',
            name='tlink',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
