# Generated by Django 3.1.3 on 2020-11-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cookie_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
